### ISSUE TITLE
Phase 1: Core NATS Connector Foundation

### ISSUE THREAD

**Issue by bjcoombs** [senapt/helidon#2]
## Summary

Implement the core NATS connector foundation for Helidon's MicroProfile Reactive Messaging framework, providing basic publish/subscribe functionality.

## Parent Issue

This is part of the larger NATS connector implementation: https://github.com/senapt/helidon/issues/1

## Scope

This phase establishes the fundamental connector architecture and basic NATS integration without JetStream features.

### Connector Structure
- [ ] Create `messaging/connectors/nats/` module directory
- [ ] Add Maven `pom.xml` with NATS Java client dependency
- [ ] Create `NatsConnector.java` implementing `Connector` interface
- [ ] Implement connector registration and lifecycle management

### Connection Management
- [ ] Create `NatsConnectionManager.java` for connection pooling
- [ ] Implement connection options builder from configuration
- [ ] Add authentication support (token and credentials)
- [ ] Add TLS configuration support
- [ ] Handle connection failures and reconnection logic

### Basic Messaging Support
- [ ] Create `NatsPublisher.java` implementing `Publisher<Message<?>>`
- [ ] Create `NatsSubscriber.java` implementing `Subscriber<Message<?>>`
- [ ] Implement `NatsMessage.java` wrapper for NATS messages
- [ ] Add message acknowledgment support

### Configuration Integration
- [ ] Define configuration schema for NATS connector
- [ ] Integrate with Helidon's config system
- [ ] Support multiple NATS server URLs
- [ ] Add connection timeout and retry configurations

### Basic Error Handling
- [ ] Implement proper exception handling
- [ ] Add logging with appropriate levels
- [ ] Handle network disconnections gracefully

## Configuration Example

```yaml
mp:
  messaging:
    connector:
      helidon-nats:
        url: "nats://localhost:4222"
        connection-timeout: "5s"
        max-reconnects: 10
        reconnect-wait: "1s"
    outgoing:
      my-channel:
        connector: helidon-nats
        subject: "my.subject"
    incoming:
      other-channel:
        connector: helidon-nats
        subject: "other.subject"
```

## Acceptance Criteria

- [ ] Basic NATS pub/sub messaging works through MicroProfile Reactive Messaging
- [ ] Connector integrates with Helidon's configuration system
- [ ] Connection management handles failures gracefully
- [ ] Unit tests cover core functionality with mock NATS
- [ ] Integration tests work with real NATS server
- [ ] Code follows Helidon coding standards and patterns

## Testing Requirements

- [ ] Unit tests using mocked NATS connections
- [ ] Integration tests with Testcontainers NATS server
- [ ] Configuration validation tests
- [ ] Connection failure scenario tests

## Dependencies

- NATS Java client library
- Helidon messaging framework
- MicroProfile Reactive Messaging API
- JUnit 5 for testing
- Testcontainers for integration tests

## Definition of Done

- All tasks completed and tested
- Code review passed
- Documentation updated
- Ready for Phase 2 (JetStream support)
