### ISSUE TITLE
Phase 2: JetStream Support for NATS Connector

### ISSUE THREAD

**Issue by bjcoombs** [senapt/helidon#3]
## Summary

Extend the NATS connector with JetStream support, enabling stream processing, persistence, and advanced delivery guarantees for Helidon applications.

## Parent Issue

This is part of the larger NATS connector implementation: https://github.com/senapt/helidon/issues/1

## Dependencies

- Requires completion of Phase 1: https://github.com/senapt/helidon/issues/2

## Scope

This phase adds JetStream capabilities to the existing core NATS connector, providing stream-based messaging with persistence and advanced acknowledgment modes.

### JetStream Integration
- [ ] Extend `NatsConnector.java` with JetStream support detection
- [ ] Create `JetStreamManager.java` for stream and consumer management
- [ ] Add JetStream context creation and configuration
- [ ] Implement stream creation and validation

### Enhanced Publishing
- [ ] Extend `NatsPublisher.java` with JetStream publishing
- [ ] Add `PublishAck` handling for delivery confirmation
- [ ] Implement synchronous and asynchronous publish modes
- [ ] Support message headers and metadata

### Stream Consumer Support
- [ ] Create `JetStreamSubscriber.java` for durable consumers
- [ ] Implement pull and push consumer patterns
- [ ] Add consumer configuration (deliver policy, ack policy, etc.)
- [ ] Support consumer groups and work queues

### Advanced Acknowledgment
- [ ] Implement at-least-once delivery semantics
- [ ] Add manual acknowledgment support
- [ ] Handle negative acknowledgments and redelivery
- [ ] Support acknowledgment timeouts

### Stream Management
- [ ] Add stream creation and configuration
- [ ] Implement consumer lifecycle management
- [ ] Support stream retention policies
- [ ] Add stream info and monitoring capabilities

## Configuration Example

```yaml
mp:
  messaging:
    connector:
      helidon-nats:
        url: "nats://localhost:4222"
        jetstream:
          enabled: true
          request-timeout: "30s"
          publish-timeout: "10s"
    outgoing:
      orders-stream:
        connector: helidon-nats
        subject: "orders.created"
        jetstream:
          stream: "ORDERS"
          ack-wait: "30s"
    incoming:
      order-processor:
        connector: helidon-nats
        subject: "orders.*"
        jetstream:
          stream: "ORDERS"
          consumer: "order-processor"
          deliver-policy: "new"
          ack-policy: "explicit"
```

## Usage Example

```java
@ApplicationScoped
public class OrderProcessor {
    
    @Incoming("order-processor")
    @Acknowledgment(Acknowledgment.Strategy.MANUAL)
    public CompletionStage<Void> processOrder(Message<Order> message) {
        return processOrderAsync(message.getPayload())
            .thenCompose(result -> message.ack())
            .exceptionally(error -> {
                message.nack(error);
                return null;
            });
    }
    
    @Outgoing("orders-stream") 
    public Multi<Order> generateOrders() {
        return Multi.createFrom().ticks().every(Duration.ofSeconds(1))
            .map(tick -> createNewOrder());
    }
}
```

## Acceptance Criteria

- [ ] JetStream publishing with acknowledgment confirmation works
- [ ] Durable consumers can process messages reliably
- [ ] Manual acknowledgment and negative acknowledgment supported
- [ ] Stream and consumer management integrated
- [ ] At-least-once delivery semantics implemented
- [ ] Configuration schema supports all JetStream features
- [ ] Integration tests validate JetStream functionality

## Testing Requirements

- [ ] Unit tests for JetStream components with mocks
- [ ] Integration tests with real NATS JetStream server
- [ ] Acknowledgment and redelivery scenario tests
- [ ] Stream lifecycle and consumer management tests
- [ ] Performance tests for throughput and latency

## Advanced Features

- [ ] Support for key-value stores (if time permits)
- [ ] Object store integration (if time permits)
- [ ] Message filtering and transformation
- [ ] Dead letter queue support

## Dependencies

- NATS Java client with JetStream support
- Completed Phase 1 core connector
- Enhanced integration test setup

## Definition of Done

- All core JetStream features implemented and tested
- Backward compatibility with Phase 1 maintained
- Performance meets expectations
- Ready for Phase 3 (Enterprise features)
EOF < /dev/null
