### ISSUE TITLE
Phase 3: Enterprise Features for NATS Connector

### ISSUE THREAD

**Issue by bjcoombs** [senapt/helidon#4]
## Summary

Add enterprise-grade features to the NATS connector including comprehensive health checks, metrics collection, advanced security, and resilience patterns.

## Parent Issue

This is part of the larger NATS connector implementation: https://github.com/senapt/helidon/issues/1

## Dependencies

- Requires completion of Phase 1: https://github.com/senapt/helidon/issues/2
- Requires completion of Phase 2: https://github.com/senapt/helidon/issues/3

## Scope

This phase transforms the NATS connector into a production-ready enterprise component with observability, security, and operational excellence features.

### Health Check Integration
- [ ] Implement `NatsHealthCheck.java` extending Helidon health framework
- [ ] Add connection health verification with ping/pong
- [ ] Include JetStream availability checks
- [ ] Monitor stream and consumer health
- [ ] Add configurable health check intervals and timeouts

### Metrics Collection
- [ ] Integrate with `microprofile/messaging/metrics/`
- [ ] Add connection pool metrics (active, idle, failed connections)
- [ ] Track message throughput (sent/received per second)
- [ ] Monitor acknowledgment rates and failures
- [ ] Include JetStream-specific metrics (stream size, consumer lag)

### Advanced Security
- [ ] Implement NKEY authentication support
- [ ] Add JWT-based authentication
- [ ] Support client certificates for mTLS
- [ ] Add credential rotation capabilities
- [ ] Implement secure credential storage integration

### Resilience Patterns
- [ ] Add circuit breaker for connection failures
- [ ] Implement exponential backoff for reconnections
- [ ] Add bulkhead pattern for connection isolation
- [ ] Support graceful degradation scenarios
- [ ] Implement timeout and retry policies

### Error Handling & Recovery
- [ ] Add comprehensive error classification
- [ ] Implement dead letter queue support
- [ ] Add poison message handling
- [ ] Support manual intervention capabilities
- [ ] Implement audit logging for failures

### Performance Optimization
- [ ] Add connection pooling optimization
- [ ] Implement message batching capabilities
- [ ] Add back-pressure handling
- [ ] Support asynchronous processing patterns
- [ ] Add memory usage optimization

## Configuration Example

```yaml
mp:
  messaging:
    connector:
      helidon-nats:
        url: "nats://localhost:4222"
        security:
          tls:
            enabled: true
            key-store: "/path/to/keystore.jks"
            trust-store: "/path/to/truststore.jks"
          auth:
            type: "nkey"
            seed: "${NATS_SEED}"
        resilience:
          circuit-breaker:
            failure-threshold: 5
            delay: "10s"
          retry:
            max-attempts: 3
            backoff: "exponential"
        health:
          check-interval: "30s"
          timeout: "5s"
        metrics:
          enabled: true
          include-jvm: true
```

## Health Check Features

- **Connection Health**: Verify NATS server connectivity
- **JetStream Health**: Check stream and consumer status  
- **Performance Health**: Monitor throughput and latency
- **Resource Health**: Check memory and connection limits

## Metrics Provided

```java
// Connection metrics
nats_connections_active_total
nats_connections_failed_total
nats_connection_duration_seconds

// Message metrics  
nats_messages_sent_total
nats_messages_received_total
nats_message_processing_duration_seconds

// JetStream metrics
nats_jetstream_stream_messages_total
nats_jetstream_consumer_lag_messages
nats_jetstream_ack_duration_seconds
```

## Acceptance Criteria

- [ ] Health checks integrate with Helidon health endpoints
- [ ] Metrics appear in Prometheus/Micrometer endpoints
- [ ] TLS and advanced authentication work correctly
- [ ] Circuit breaker prevents cascade failures
- [ ] Dead letter queue handles poison messages
- [ ] Performance meets enterprise requirements
- [ ] Error handling provides actionable diagnostics

## Testing Requirements

- [ ] Health check endpoint integration tests
- [ ] Metrics validation with test metrics registry
- [ ] Security feature tests with certificates and tokens
- [ ] Resilience pattern tests (failure scenarios)
- [ ] Performance benchmarks vs direct NATS client
- [ ] Load testing with realistic enterprise scenarios

## Security Testing

- [ ] TLS configuration validation
- [ ] Authentication mechanism testing
- [ ] Certificate rotation testing
- [ ] Credential security scanning

## Performance Targets

- [ ] Latency: p99 < 10ms for message publishing
- [ ] Throughput: > 10,000 messages/second
- [ ] Memory: < 100MB baseline usage
- [ ] CPU: < 5% baseline usage under normal load

## Dependencies

- Helidon health framework
- Helidon metrics integration
- NATS security features
- Performance testing tools

## Definition of Done

- All enterprise features implemented and tested
- Security review completed and passed
- Performance benchmarks meet targets
- Production readiness checklist completed
- Ready for Phase 4 (Documentation)
